// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/insyncpb.proto

package insyncpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Тип файла для передачи метаданных о файлах и директориях
type FileEntry struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RelativePath string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	SizeBytes    uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ModifiedUnix uint64                 `protobuf:"varint,4,opt,name=modified_unix,json=modifiedUnix,proto3" json:"modified_unix,omitempty"`
	Hash         string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	IsDirectory  bool                   `protobuf:"varint,6,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	FileId       uint64                 `protobuf:"varint,7,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	// Количество файлов в поддереве (для директорий), учитывая все вложенные файлы и директории и саму папку
	SubtreeSize   uint64 `protobuf:"varint,8,opt,name=subtree_size,json=subtreeSize,proto3" json:"subtree_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_proto_insyncpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{0}
}

func (x *FileEntry) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *FileEntry) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileEntry) GetModifiedUnix() uint64 {
	if x != nil {
		return x.ModifiedUnix
	}
	return 0
}

func (x *FileEntry) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileEntry) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *FileEntry) GetFileId() uint64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *FileEntry) GetSubtreeSize() uint64 {
	if x != nil {
		return x.SubtreeSize
	}
	return 0
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixTime      uint64                 `protobuf:"varint,1,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	Files         []*FileEntry           `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_proto_insyncpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{1}
}

func (x *Snapshot) GetUnixTime() uint64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

func (x *Snapshot) GetFiles() []*FileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

// Тип для запроса и ответа при получении списка файлов
type GetSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootName      string                 `protobuf:"bytes,1,opt,name=root_name,json=rootName,proto3" json:"root_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_proto_insyncpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetSnapshotRequest) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

type GetSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	mi := &file_proto_insyncpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{3}
}

func (x *GetSnapshotResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// Тип для запроса и ответа при получении файла
type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootName      string                 `protobuf:"bytes,1,opt,name=root_name,json=rootName,proto3" json:"root_name,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_proto_insyncpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{4}
}

func (x *GetFileRequest) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

func (x *GetFileRequest) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         *FileChunk             `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_proto_insyncpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileResponse) GetChunk() *FileChunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// Тип запроса для загрузки файла
type PutFileInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootName      string                 `protobuf:"bytes,1,opt,name=root_name,json=rootName,proto3" json:"root_name,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFileInit) Reset() {
	*x = PutFileInit{}
	mi := &file_proto_insyncpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFileInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileInit) ProtoMessage() {}

func (x *PutFileInit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileInit.ProtoReflect.Descriptor instead.
func (*PutFileInit) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{6}
}

func (x *PutFileInit) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

func (x *PutFileInit) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

type PutFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PutFileRequest_Init
	//	*PutFileRequest_Chunk
	Payload       isPutFileRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFileRequest) Reset() {
	*x = PutFileRequest{}
	mi := &file_proto_insyncpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileRequest) ProtoMessage() {}

func (x *PutFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileRequest.ProtoReflect.Descriptor instead.
func (*PutFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{7}
}

func (x *PutFileRequest) GetPayload() isPutFileRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PutFileRequest) GetInit() *PutFileInit {
	if x != nil {
		if x, ok := x.Payload.(*PutFileRequest_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *PutFileRequest) GetChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Payload.(*PutFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isPutFileRequest_Payload interface {
	isPutFileRequest_Payload()
}

type PutFileRequest_Init struct {
	Init *PutFileInit `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type PutFileRequest_Chunk struct {
	Chunk *FileChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*PutFileRequest_Init) isPutFileRequest_Payload() {}

func (*PutFileRequest_Chunk) isPutFileRequest_Payload() {}

// Тип запроса для удаления файла
type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootName      string                 `protobuf:"bytes,1,opt,name=root_name,json=rootName,proto3" json:"root_name,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_proto_insyncpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFileRequest) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

func (x *DeleteFileRequest) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

// Тип запроса для переименования файла
type RenameFileRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RootName        string                 `protobuf:"bytes,1,opt,name=root_name,json=rootName,proto3" json:"root_name,omitempty"`
	OldRelativePath string                 `protobuf:"bytes,2,opt,name=old_relative_path,json=oldRelativePath,proto3" json:"old_relative_path,omitempty"`
	NewRelativePath string                 `protobuf:"bytes,3,opt,name=new_relative_path,json=newRelativePath,proto3" json:"new_relative_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RenameFileRequest) Reset() {
	*x = RenameFileRequest{}
	mi := &file_proto_insyncpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileRequest) ProtoMessage() {}

func (x *RenameFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileRequest.ProtoReflect.Descriptor instead.
func (*RenameFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{9}
}

func (x *RenameFileRequest) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

func (x *RenameFileRequest) GetOldRelativePath() string {
	if x != nil {
		return x.OldRelativePath
	}
	return ""
}

func (x *RenameFileRequest) GetNewRelativePath() string {
	if x != nil {
		return x.NewRelativePath
	}
	return ""
}

// Чанк файла
type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_insyncpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{10}
}

func (x *FileChunk) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_insyncpb_proto protoreflect.FileDescriptor

const file_proto_insyncpb_proto_rawDesc = "" +
	"\n" +
	"\x14proto/insyncpb.proto\x12\binsyncpb\x1a\x1bgoogle/protobuf/empty.proto\"\xe7\x01\n" +
	"\tFileEntry\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12#\n" +
	"\rmodified_unix\x18\x04 \x01(\x04R\fmodifiedUnix\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12!\n" +
	"\fis_directory\x18\x06 \x01(\bR\visDirectory\x12\x17\n" +
	"\afile_id\x18\a \x01(\x04R\x06fileId\x12!\n" +
	"\fsubtree_size\x18\b \x01(\x04R\vsubtreeSize\"R\n" +
	"\bSnapshot\x12\x1b\n" +
	"\tunix_time\x18\x01 \x01(\x04R\bunixTime\x12)\n" +
	"\x05files\x18\x02 \x03(\v2\x13.insyncpb.FileEntryR\x05files\"1\n" +
	"\x12GetSnapshotRequest\x12\x1b\n" +
	"\troot_name\x18\x01 \x01(\tR\brootName\"E\n" +
	"\x13GetSnapshotResponse\x12.\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x12.insyncpb.SnapshotR\bsnapshot\"R\n" +
	"\x0eGetFileRequest\x12\x1b\n" +
	"\troot_name\x18\x01 \x01(\tR\brootName\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\"<\n" +
	"\x0fGetFileResponse\x12)\n" +
	"\x05chunk\x18\x01 \x01(\v2\x13.insyncpb.FileChunkR\x05chunk\"O\n" +
	"\vPutFileInit\x12\x1b\n" +
	"\troot_name\x18\x01 \x01(\tR\brootName\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\"u\n" +
	"\x0ePutFileRequest\x12+\n" +
	"\x04init\x18\x01 \x01(\v2\x15.insyncpb.PutFileInitH\x00R\x04init\x12+\n" +
	"\x05chunk\x18\x02 \x01(\v2\x13.insyncpb.FileChunkH\x00R\x05chunkB\t\n" +
	"\apayload\"U\n" +
	"\x11DeleteFileRequest\x12\x1b\n" +
	"\troot_name\x18\x01 \x01(\tR\brootName\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\"\x88\x01\n" +
	"\x11RenameFileRequest\x12\x1b\n" +
	"\troot_name\x18\x01 \x01(\tR\brootName\x12*\n" +
	"\x11old_relative_path\x18\x02 \x01(\tR\x0foldRelativePath\x12*\n" +
	"\x11new_relative_path\x18\x03 \x01(\tR\x0fnewRelativePath\"5\n" +
	"\tFileChunk\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data2\xe4\x02\n" +
	"\x0fFileSyncService\x12J\n" +
	"\vGetSnapshot\x12\x1c.insyncpb.GetSnapshotRequest\x1a\x1d.insyncpb.GetSnapshotResponse\x12@\n" +
	"\aGetFile\x12\x18.insyncpb.GetFileRequest\x1a\x19.insyncpb.GetFileResponse0\x01\x12=\n" +
	"\aPutFile\x12\x18.insyncpb.PutFileRequest\x1a\x16.google.protobuf.Empty(\x01\x12A\n" +
	"\n" +
	"DeleteFile\x12\x1b.insyncpb.DeleteFileRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\n" +
	"RenameFile\x12\x1b.insyncpb.RenameFileRequest\x1a\x16.google.protobuf.EmptyB+Z)internal/transport/grpc/insyncpb;insyncpbb\x06proto3"

var (
	file_proto_insyncpb_proto_rawDescOnce sync.Once
	file_proto_insyncpb_proto_rawDescData []byte
)

func file_proto_insyncpb_proto_rawDescGZIP() []byte {
	file_proto_insyncpb_proto_rawDescOnce.Do(func() {
		file_proto_insyncpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_insyncpb_proto_rawDesc), len(file_proto_insyncpb_proto_rawDesc)))
	})
	return file_proto_insyncpb_proto_rawDescData
}

var file_proto_insyncpb_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_insyncpb_proto_goTypes = []any{
	(*FileEntry)(nil),           // 0: insyncpb.FileEntry
	(*Snapshot)(nil),            // 1: insyncpb.Snapshot
	(*GetSnapshotRequest)(nil),  // 2: insyncpb.GetSnapshotRequest
	(*GetSnapshotResponse)(nil), // 3: insyncpb.GetSnapshotResponse
	(*GetFileRequest)(nil),      // 4: insyncpb.GetFileRequest
	(*GetFileResponse)(nil),     // 5: insyncpb.GetFileResponse
	(*PutFileInit)(nil),         // 6: insyncpb.PutFileInit
	(*PutFileRequest)(nil),      // 7: insyncpb.PutFileRequest
	(*DeleteFileRequest)(nil),   // 8: insyncpb.DeleteFileRequest
	(*RenameFileRequest)(nil),   // 9: insyncpb.RenameFileRequest
	(*FileChunk)(nil),           // 10: insyncpb.FileChunk
	(*emptypb.Empty)(nil),       // 11: google.protobuf.Empty
}
var file_proto_insyncpb_proto_depIdxs = []int32{
	0,  // 0: insyncpb.Snapshot.files:type_name -> insyncpb.FileEntry
	1,  // 1: insyncpb.GetSnapshotResponse.snapshot:type_name -> insyncpb.Snapshot
	10, // 2: insyncpb.GetFileResponse.chunk:type_name -> insyncpb.FileChunk
	6,  // 3: insyncpb.PutFileRequest.init:type_name -> insyncpb.PutFileInit
	10, // 4: insyncpb.PutFileRequest.chunk:type_name -> insyncpb.FileChunk
	2,  // 5: insyncpb.FileSyncService.GetSnapshot:input_type -> insyncpb.GetSnapshotRequest
	4,  // 6: insyncpb.FileSyncService.GetFile:input_type -> insyncpb.GetFileRequest
	7,  // 7: insyncpb.FileSyncService.PutFile:input_type -> insyncpb.PutFileRequest
	8,  // 8: insyncpb.FileSyncService.DeleteFile:input_type -> insyncpb.DeleteFileRequest
	9,  // 9: insyncpb.FileSyncService.RenameFile:input_type -> insyncpb.RenameFileRequest
	3,  // 10: insyncpb.FileSyncService.GetSnapshot:output_type -> insyncpb.GetSnapshotResponse
	5,  // 11: insyncpb.FileSyncService.GetFile:output_type -> insyncpb.GetFileResponse
	11, // 12: insyncpb.FileSyncService.PutFile:output_type -> google.protobuf.Empty
	11, // 13: insyncpb.FileSyncService.DeleteFile:output_type -> google.protobuf.Empty
	11, // 14: insyncpb.FileSyncService.RenameFile:output_type -> google.protobuf.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_insyncpb_proto_init() }
func file_proto_insyncpb_proto_init() {
	if File_proto_insyncpb_proto != nil {
		return
	}
	file_proto_insyncpb_proto_msgTypes[7].OneofWrappers = []any{
		(*PutFileRequest_Init)(nil),
		(*PutFileRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_insyncpb_proto_rawDesc), len(file_proto_insyncpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_insyncpb_proto_goTypes,
		DependencyIndexes: file_proto_insyncpb_proto_depIdxs,
		MessageInfos:      file_proto_insyncpb_proto_msgTypes,
	}.Build()
	File_proto_insyncpb_proto = out.File
	file_proto_insyncpb_proto_goTypes = nil
	file_proto_insyncpb_proto_depIdxs = nil
}
