// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/insyncpb.proto

package insyncpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Тип файла для передачи метаданных о файлах и директориях
type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootName      string                 `protobuf:"bytes,1,opt,name=root_name,json=rootName,proto3" json:"root_name,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	SizeBytes     uint32                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ModifiedUnix  uint32                 `protobuf:"varint,4,opt,name=modified_unix,json=modifiedUnix,proto3" json:"modified_unix,omitempty"`
	Hash          string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	IsDirectory   bool                   `protobuf:"varint,6,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_proto_insyncpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{0}
}

func (x *FileMetadata) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

func (x *FileMetadata) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *FileMetadata) GetSizeBytes() uint32 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileMetadata) GetModifiedUnix() uint32 {
	if x != nil {
		return x.ModifiedUnix
	}
	return 0
}

func (x *FileMetadata) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileMetadata) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

// Тип для запроса и ответа при получении списка файлов
type GetFileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootName      string                 `protobuf:"bytes,1,opt,name=root_name,json=rootName,proto3" json:"root_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileListRequest) Reset() {
	*x = GetFileListRequest{}
	mi := &file_proto_insyncpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileListRequest) ProtoMessage() {}

func (x *GetFileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileListRequest.ProtoReflect.Descriptor instead.
func (*GetFileListRequest) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{1}
}

func (x *GetFileListRequest) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

type GetFileListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileMetadata        `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileListResponse) Reset() {
	*x = GetFileListResponse{}
	mi := &file_proto_insyncpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileListResponse) ProtoMessage() {}

func (x *GetFileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileListResponse.ProtoReflect.Descriptor instead.
func (*GetFileListResponse) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetFileListResponse) GetFiles() []*FileMetadata {
	if x != nil {
		return x.Files
	}
	return nil
}

// Тип для запроса и ответа при получении файла
type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootName      string                 `protobuf:"bytes,1,opt,name=root_name,json=rootName,proto3" json:"root_name,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_proto_insyncpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileRequest) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

func (x *GetFileRequest) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         *FileChunk             `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_proto_insyncpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{4}
}

func (x *GetFileResponse) GetChunk() *FileChunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// Тип запроса для загрузки файла
type PutFileInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootName      string                 `protobuf:"bytes,1,opt,name=root_name,json=rootName,proto3" json:"root_name,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFileInit) Reset() {
	*x = PutFileInit{}
	mi := &file_proto_insyncpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFileInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileInit) ProtoMessage() {}

func (x *PutFileInit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileInit.ProtoReflect.Descriptor instead.
func (*PutFileInit) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{5}
}

func (x *PutFileInit) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

func (x *PutFileInit) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

type PutFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PutFileRequest_Init
	//	*PutFileRequest_Chunk
	Payload       isPutFileRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFileRequest) Reset() {
	*x = PutFileRequest{}
	mi := &file_proto_insyncpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileRequest) ProtoMessage() {}

func (x *PutFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileRequest.ProtoReflect.Descriptor instead.
func (*PutFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{6}
}

func (x *PutFileRequest) GetPayload() isPutFileRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PutFileRequest) GetInit() *PutFileInit {
	if x != nil {
		if x, ok := x.Payload.(*PutFileRequest_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *PutFileRequest) GetChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Payload.(*PutFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isPutFileRequest_Payload interface {
	isPutFileRequest_Payload()
}

type PutFileRequest_Init struct {
	Init *PutFileInit `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type PutFileRequest_Chunk struct {
	Chunk *FileChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*PutFileRequest_Init) isPutFileRequest_Payload() {}

func (*PutFileRequest_Chunk) isPutFileRequest_Payload() {}

// Тип запроса для удаления файла
type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootName      string                 `protobuf:"bytes,1,opt,name=root_name,json=rootName,proto3" json:"root_name,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_proto_insyncpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFileRequest) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

func (x *DeleteFileRequest) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

// Тип запроса для переименования файла
type RenameFileRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RootName        string                 `protobuf:"bytes,1,opt,name=root_name,json=rootName,proto3" json:"root_name,omitempty"`
	OldRelativePath string                 `protobuf:"bytes,2,opt,name=old_relative_path,json=oldRelativePath,proto3" json:"old_relative_path,omitempty"`
	NewRelativePath string                 `protobuf:"bytes,3,opt,name=new_relative_path,json=newRelativePath,proto3" json:"new_relative_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RenameFileRequest) Reset() {
	*x = RenameFileRequest{}
	mi := &file_proto_insyncpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileRequest) ProtoMessage() {}

func (x *RenameFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileRequest.ProtoReflect.Descriptor instead.
func (*RenameFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{8}
}

func (x *RenameFileRequest) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

func (x *RenameFileRequest) GetOldRelativePath() string {
	if x != nil {
		return x.OldRelativePath
	}
	return ""
}

func (x *RenameFileRequest) GetNewRelativePath() string {
	if x != nil {
		return x.NewRelativePath
	}
	return ""
}

// Чанк файла
type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_insyncpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insyncpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_insyncpb_proto_rawDescGZIP(), []int{9}
}

func (x *FileChunk) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_insyncpb_proto protoreflect.FileDescriptor

const file_proto_insyncpb_proto_rawDesc = "" +
	"\n" +
	"\x14proto/insyncpb.proto\x12\binsyncpb\x1a\x1bgoogle/protobuf/empty.proto\"\xcb\x01\n" +
	"\fFileMetadata\x12\x1b\n" +
	"\troot_name\x18\x01 \x01(\tR\brootName\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\rR\tsizeBytes\x12#\n" +
	"\rmodified_unix\x18\x04 \x01(\rR\fmodifiedUnix\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12!\n" +
	"\fis_directory\x18\x06 \x01(\bR\visDirectory\"1\n" +
	"\x12GetFileListRequest\x12\x1b\n" +
	"\troot_name\x18\x01 \x01(\tR\brootName\"C\n" +
	"\x13GetFileListResponse\x12,\n" +
	"\x05files\x18\x01 \x03(\v2\x16.insyncpb.FileMetadataR\x05files\"R\n" +
	"\x0eGetFileRequest\x12\x1b\n" +
	"\troot_name\x18\x01 \x01(\tR\brootName\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\"<\n" +
	"\x0fGetFileResponse\x12)\n" +
	"\x05chunk\x18\x01 \x01(\v2\x13.insyncpb.FileChunkR\x05chunk\"O\n" +
	"\vPutFileInit\x12\x1b\n" +
	"\troot_name\x18\x01 \x01(\tR\brootName\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\"u\n" +
	"\x0ePutFileRequest\x12+\n" +
	"\x04init\x18\x01 \x01(\v2\x15.insyncpb.PutFileInitH\x00R\x04init\x12+\n" +
	"\x05chunk\x18\x02 \x01(\v2\x13.insyncpb.FileChunkH\x00R\x05chunkB\t\n" +
	"\apayload\"U\n" +
	"\x11DeleteFileRequest\x12\x1b\n" +
	"\troot_name\x18\x01 \x01(\tR\brootName\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\"\x88\x01\n" +
	"\x11RenameFileRequest\x12\x1b\n" +
	"\troot_name\x18\x01 \x01(\tR\brootName\x12*\n" +
	"\x11old_relative_path\x18\x02 \x01(\tR\x0foldRelativePath\x12*\n" +
	"\x11new_relative_path\x18\x03 \x01(\tR\x0fnewRelativePath\"5\n" +
	"\tFileChunk\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data2\xe4\x02\n" +
	"\x0fFileSyncService\x12J\n" +
	"\vGetFileList\x12\x1c.insyncpb.GetFileListRequest\x1a\x1d.insyncpb.GetFileListResponse\x12@\n" +
	"\aGetFile\x12\x18.insyncpb.GetFileRequest\x1a\x19.insyncpb.GetFileResponse0\x01\x12=\n" +
	"\aPutFile\x12\x18.insyncpb.PutFileRequest\x1a\x16.google.protobuf.Empty(\x01\x12A\n" +
	"\n" +
	"DeleteFile\x12\x1b.insyncpb.DeleteFileRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\n" +
	"RenameFile\x12\x1b.insyncpb.RenameFileRequest\x1a\x16.google.protobuf.EmptyB+Z)internal/transport/grpc/insyncpb;insyncpbb\x06proto3"

var (
	file_proto_insyncpb_proto_rawDescOnce sync.Once
	file_proto_insyncpb_proto_rawDescData []byte
)

func file_proto_insyncpb_proto_rawDescGZIP() []byte {
	file_proto_insyncpb_proto_rawDescOnce.Do(func() {
		file_proto_insyncpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_insyncpb_proto_rawDesc), len(file_proto_insyncpb_proto_rawDesc)))
	})
	return file_proto_insyncpb_proto_rawDescData
}

var file_proto_insyncpb_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_insyncpb_proto_goTypes = []any{
	(*FileMetadata)(nil),        // 0: insyncpb.FileMetadata
	(*GetFileListRequest)(nil),  // 1: insyncpb.GetFileListRequest
	(*GetFileListResponse)(nil), // 2: insyncpb.GetFileListResponse
	(*GetFileRequest)(nil),      // 3: insyncpb.GetFileRequest
	(*GetFileResponse)(nil),     // 4: insyncpb.GetFileResponse
	(*PutFileInit)(nil),         // 5: insyncpb.PutFileInit
	(*PutFileRequest)(nil),      // 6: insyncpb.PutFileRequest
	(*DeleteFileRequest)(nil),   // 7: insyncpb.DeleteFileRequest
	(*RenameFileRequest)(nil),   // 8: insyncpb.RenameFileRequest
	(*FileChunk)(nil),           // 9: insyncpb.FileChunk
	(*emptypb.Empty)(nil),       // 10: google.protobuf.Empty
}
var file_proto_insyncpb_proto_depIdxs = []int32{
	0,  // 0: insyncpb.GetFileListResponse.files:type_name -> insyncpb.FileMetadata
	9,  // 1: insyncpb.GetFileResponse.chunk:type_name -> insyncpb.FileChunk
	5,  // 2: insyncpb.PutFileRequest.init:type_name -> insyncpb.PutFileInit
	9,  // 3: insyncpb.PutFileRequest.chunk:type_name -> insyncpb.FileChunk
	1,  // 4: insyncpb.FileSyncService.GetFileList:input_type -> insyncpb.GetFileListRequest
	3,  // 5: insyncpb.FileSyncService.GetFile:input_type -> insyncpb.GetFileRequest
	6,  // 6: insyncpb.FileSyncService.PutFile:input_type -> insyncpb.PutFileRequest
	7,  // 7: insyncpb.FileSyncService.DeleteFile:input_type -> insyncpb.DeleteFileRequest
	8,  // 8: insyncpb.FileSyncService.RenameFile:input_type -> insyncpb.RenameFileRequest
	2,  // 9: insyncpb.FileSyncService.GetFileList:output_type -> insyncpb.GetFileListResponse
	4,  // 10: insyncpb.FileSyncService.GetFile:output_type -> insyncpb.GetFileResponse
	10, // 11: insyncpb.FileSyncService.PutFile:output_type -> google.protobuf.Empty
	10, // 12: insyncpb.FileSyncService.DeleteFile:output_type -> google.protobuf.Empty
	10, // 13: insyncpb.FileSyncService.RenameFile:output_type -> google.protobuf.Empty
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_insyncpb_proto_init() }
func file_proto_insyncpb_proto_init() {
	if File_proto_insyncpb_proto != nil {
		return
	}
	file_proto_insyncpb_proto_msgTypes[6].OneofWrappers = []any{
		(*PutFileRequest_Init)(nil),
		(*PutFileRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_insyncpb_proto_rawDesc), len(file_proto_insyncpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_insyncpb_proto_goTypes,
		DependencyIndexes: file_proto_insyncpb_proto_depIdxs,
		MessageInfos:      file_proto_insyncpb_proto_msgTypes,
	}.Build()
	File_proto_insyncpb_proto = out.File
	file_proto_insyncpb_proto_goTypes = nil
	file_proto_insyncpb_proto_depIdxs = nil
}
