tls: &tls
  ca_cert_dir: "../certs"
  ca_cert_filename: "ca"
  ca_cert_extension: ".crt"

chunk_size_in_bytes: &chunk_size 1024

server_domain: &mdns_server_domain "local."
server_service_type: &mdns_server_service_type "_grpc._tcp"
service_name: &service_name "insincpb.FileSyncService"

server:
  ip: ""
  port: 50051
  network_type: "tcp"
  service_name: *service_name
  chunk_size_in_bytes: *chunk_size

  tls:
    <<: *tls
    server_cert_dir: "../certs"
    server_cert_filename: "server"
    server_cert_extension: ".crt"

    server_key_dir: "../certs"
    server_key_filename: "server"
    server_key_extension: ".key"

client:
    resolver_scheme: "mdns"
    server_service_name: *service_name
    server_ip: ""
    server_port: 50051
    server_network_type: "tcp"
    load_balancing_policy: "pick_first"
    should_use_health_check: true
    chunk_size_in_bytes: *chunk_size
    rpc_timeout: 5

    rpc_retry_policy:
      max_attempts: 3
      initial_backoff_seconds: 1
      max_backoff_seconds: 10
      backoff_multiplier: 1.5
      retryable_status_codes: 
        - "UNAVAILABLE"
        - "RESOURCE_EXHAUSTED"

    connection_config:
      base_delay_seconds: 1
      multiplier: 1.6
      max_delay_seconds: 120
      jitter: 0.2
      min_connect_timeout_seconds: 20

    tls:
      <<: *tls
      client_cert_dir: "../certs"
      client_cert_filename: "client"
      client_cert_extension: ".crt"

      client_key_dir: "../certs"
      client_key_filename: "client"
      client_key_extension: ".key"

db:
  dir: "../db"
  file_name: "app.db"
  pragma: "?_pragma=journal_mode(wal)&_pragma=foreign_keys(1)"

logger:
  should_log_to_file: true
  log_file_directory: "../logs"
  log_file_name: "logs"
  log_file_extension: "txt"
  log_level: "debug"


mdns_server:
  service_type: *mdns_server_service_type
  domain: *mdns_server_domain
  port: 50051
  # формат "eth0;wlan0;Беспроводная сеть 5;8"
  # поддерживает как имя интерфейса, так и индекс интерфейса
  interfaces: "Беспроводная сеть 5"

device_id_resolver:
  device_id_dir: "../deviceid"
  device_id_file_name: "device_id.txt"

mdns_browser:
  server_service_type: *mdns_server_service_type
  server_domain: *mdns_server_domain
  # формат "eth0;wlan0;Беспроводная сеть 5;8"
  # поддерживает как имя интерфейса, так и индекс интерфейса
  interfaces: "Беспроводная сеть 5"
