syntax = "proto3";

package insyncpb;

option go_package = "internal/transport/grpc/insyncpb;insyncpb";

import "google/protobuf/empty.proto";


// Тип файла для передачи метаданных о файлах и директориях
message FileEntry {
    string root_name = 1;
    string relative_path = 2;
    uint32 size_bytes = 3;
    uint32 modified_unix = 4;
    string hash = 5;
    bool is_directory = 6;
}


// Тип для запроса и ответа при получении списка файлов
message GetFileListRequest {
    string root_name = 1;
}

message GetFileListResponse {
    repeated FileEntry files = 1;
}

// Тип для запроса и ответа при получении файла
message GetFileRequest {
    string root_name = 1;
    string relative_path = 2;
}

message GetFileResponse {
    FileChunk chunk = 1;
}

// Тип запроса для загрузки файла
message PutFileInit {
    string root_name = 1;
    string relative_path = 2;
}

message PutFileRequest {
    oneof payload {
        PutFileInit init = 1;
        FileChunk chunk = 2;
    }
}

// Тип запроса для удаления файла
message DeleteFileRequest {
    string root_name = 1;
    string relative_path = 2;
}


// Тип запроса для переименования файла
message RenameFileRequest {
    string root_name = 1;
    string old_relative_path = 2;
    string new_relative_path = 3;
}

// Чанк файла
message FileChunk {
    uint32 index = 1;
    bytes data = 2;
}

// Сервис для синхронизации файлов
service FileSyncService {
    rpc GetFileList(GetFileListRequest) returns (GetFileListResponse);
    rpc GetFile(GetFileRequest) returns (stream GetFileResponse);
    rpc PutFile(stream PutFileRequest) returns (google.protobuf.Empty);
    rpc DeleteFile(DeleteFileRequest) returns (google.protobuf.Empty);
    rpc RenameFile(RenameFileRequest) returns (google.protobuf.Empty);
}