syntax = "proto3";

package insyncpb;

option go_package = "internal/transport/grpc/insyncpb;insyncpb";

import "google/protobuf/empty.proto";


// Тип файла для передачи метаданных о файлах и директориях
message FileEntry {
    string relative_path = 2;
    uint64 size_bytes = 3;
    uint64 modified_unix = 4;
    string hash = 5;
    bool is_directory = 6;
    uint64 file_id = 7;
    // Количество файлов в поддереве (для директорий), учитывая все вложенные файлы и директории и саму папку
    uint64 subtree_size = 8; 
}

message Snapshot {
    uint64 unix_time = 1;
    repeated FileEntry files = 2;
}


// Тип для запроса и ответа при получении списка файлов
message GetSnapshotRequest {
    string root_name = 1;
}

message GetSnapshotResponse {
    Snapshot snapshot = 1;
}

// Тип для запроса и ответа при получении файла
message GetFileRequest {
    string root_name = 1;
    string relative_path = 2;
}

message GetFileResponse {
    FileChunk chunk = 1;
}

// Тип запроса для загрузки файла
message PutFileInit {
    string root_name = 1;
    string relative_path = 2;
}

message PutFileRequest {
    oneof payload {
        PutFileInit init = 1;
        FileChunk chunk = 2;
    }
}

// Тип запроса для удаления файла
message DeleteFileRequest {
    string root_name = 1;
    string relative_path = 2;
}


// Тип запроса для переименования файла
message RenameFileRequest {
    string root_name = 1;
    string old_relative_path = 2;
    string new_relative_path = 3;
}

// Чанк файла
message FileChunk {
    uint64 index = 1;
    bytes data = 2;
}

// Сервис для синхронизации файлов
service FileSyncService {
    rpc GetSnapshot(GetSnapshotRequest) returns (GetSnapshotResponse);
    rpc GetFile(GetFileRequest) returns (stream GetFileResponse);
    rpc PutFile(stream PutFileRequest) returns (google.protobuf.Empty);
    rpc DeleteFile(DeleteFileRequest) returns (google.protobuf.Empty);
    rpc RenameFile(RenameFileRequest) returns (google.protobuf.Empty);
}