// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/sync.proto

package sync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Тип файла для передачи метаданных о файлах и директориях
type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUuid      string                 `protobuf:"bytes,1,opt,name=file_uuid,json=fileUuid,proto3" json:"file_uuid,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	SizeBytes     uint32                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ModifiedUnix  uint32                 `protobuf:"varint,4,opt,name=modified_unix,json=modifiedUnix,proto3" json:"modified_unix,omitempty"`
	Hash          string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	IsDirectory   bool                   `protobuf:"varint,6,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_proto_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{0}
}

func (x *FileMetadata) GetFileUuid() string {
	if x != nil {
		return x.FileUuid
	}
	return ""
}

func (x *FileMetadata) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *FileMetadata) GetSizeBytes() uint32 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileMetadata) GetModifiedUnix() uint32 {
	if x != nil {
		return x.ModifiedUnix
	}
	return 0
}

func (x *FileMetadata) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileMetadata) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

// Тип для запроса и ответа при получении списка файлов
type GetFileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootName      string                 `protobuf:"bytes,1,opt,name=root_name,json=rootName,proto3" json:"root_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileListRequest) Reset() {
	*x = GetFileListRequest{}
	mi := &file_proto_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileListRequest) ProtoMessage() {}

func (x *GetFileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileListRequest.ProtoReflect.Descriptor instead.
func (*GetFileListRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{1}
}

func (x *GetFileListRequest) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

type GetFileListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileMetadata        `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileListResponse) Reset() {
	*x = GetFileListResponse{}
	mi := &file_proto_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileListResponse) ProtoMessage() {}

func (x *GetFileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileListResponse.ProtoReflect.Descriptor instead.
func (*GetFileListResponse) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{2}
}

func (x *GetFileListResponse) GetFiles() []*FileMetadata {
	if x != nil {
		return x.Files
	}
	return nil
}

// Тип для запроса и ответа при получении файла
type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootName      string                 `protobuf:"bytes,1,opt,name=root_name,json=rootName,proto3" json:"root_name,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_proto_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileRequest) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

func (x *GetFileRequest) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         *FileChunk             `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_proto_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{4}
}

func (x *GetFileResponse) GetChunk() *FileChunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type PutFileInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootName      string                 `protobuf:"bytes,1,opt,name=root_name,json=rootName,proto3" json:"root_name,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFileInit) Reset() {
	*x = PutFileInit{}
	mi := &file_proto_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFileInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileInit) ProtoMessage() {}

func (x *PutFileInit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileInit.ProtoReflect.Descriptor instead.
func (*PutFileInit) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{5}
}

func (x *PutFileInit) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

func (x *PutFileInit) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

type PutFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PutFileRequest_Init
	//	*PutFileRequest_Chunk
	Payload       isPutFileRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFileRequest) Reset() {
	*x = PutFileRequest{}
	mi := &file_proto_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileRequest) ProtoMessage() {}

func (x *PutFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileRequest.ProtoReflect.Descriptor instead.
func (*PutFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{6}
}

func (x *PutFileRequest) GetPayload() isPutFileRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PutFileRequest) GetInit() *PutFileInit {
	if x != nil {
		if x, ok := x.Payload.(*PutFileRequest_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *PutFileRequest) GetChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Payload.(*PutFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isPutFileRequest_Payload interface {
	isPutFileRequest_Payload()
}

type PutFileRequest_Init struct {
	Init *PutFileInit `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type PutFileRequest_Chunk struct {
	Chunk *FileChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*PutFileRequest_Init) isPutFileRequest_Payload() {}

func (*PutFileRequest_Chunk) isPutFileRequest_Payload() {}

type PutFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFileResponse) Reset() {
	*x = PutFileResponse{}
	mi := &file_proto_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileResponse) ProtoMessage() {}

func (x *PutFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileResponse.ProtoReflect.Descriptor instead.
func (*PutFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{7}
}

func (x *PutFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PutFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Тип запроса и ответа для удаления файла
type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootName      string                 `protobuf:"bytes,1,opt,name=root_name,json=rootName,proto3" json:"root_name,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_proto_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFileRequest) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

func (x *DeleteFileRequest) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_proto_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Тип запроса и ответа для переименования файла
type RenameFileRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RootName        string                 `protobuf:"bytes,1,opt,name=root_name,json=rootName,proto3" json:"root_name,omitempty"`
	FileUuid        string                 `protobuf:"bytes,2,opt,name=file_uuid,json=fileUuid,proto3" json:"file_uuid,omitempty"`
	NewRelativePath string                 `protobuf:"bytes,3,opt,name=new_relative_path,json=newRelativePath,proto3" json:"new_relative_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RenameFileRequest) Reset() {
	*x = RenameFileRequest{}
	mi := &file_proto_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileRequest) ProtoMessage() {}

func (x *RenameFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileRequest.ProtoReflect.Descriptor instead.
func (*RenameFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{10}
}

func (x *RenameFileRequest) GetRootName() string {
	if x != nil {
		return x.RootName
	}
	return ""
}

func (x *RenameFileRequest) GetFileUuid() string {
	if x != nil {
		return x.FileUuid
	}
	return ""
}

func (x *RenameFileRequest) GetNewRelativePath() string {
	if x != nil {
		return x.NewRelativePath
	}
	return ""
}

type RenameFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFileResponse) Reset() {
	*x = RenameFileResponse{}
	mi := &file_proto_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileResponse) ProtoMessage() {}

func (x *RenameFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileResponse.ProtoReflect.Descriptor instead.
func (*RenameFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{11}
}

func (x *RenameFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RenameFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Чанк файла
type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_sync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_sync_proto_rawDescGZIP(), []int{12}
}

func (x *FileChunk) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_sync_proto protoreflect.FileDescriptor

const file_proto_sync_proto_rawDesc = "" +
	"\n" +
	"\x10proto/sync.proto\x12\x04sync\"\xcb\x01\n" +
	"\fFileMetadata\x12\x1b\n" +
	"\tfile_uuid\x18\x01 \x01(\tR\bfileUuid\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\rR\tsizeBytes\x12#\n" +
	"\rmodified_unix\x18\x04 \x01(\rR\fmodifiedUnix\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12!\n" +
	"\fis_directory\x18\x06 \x01(\bR\visDirectory\"1\n" +
	"\x12GetFileListRequest\x12\x1b\n" +
	"\troot_name\x18\x01 \x01(\tR\brootName\"?\n" +
	"\x13GetFileListResponse\x12(\n" +
	"\x05files\x18\x01 \x03(\v2\x12.sync.FileMetadataR\x05files\"R\n" +
	"\x0eGetFileRequest\x12\x1b\n" +
	"\troot_name\x18\x01 \x01(\tR\brootName\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\"8\n" +
	"\x0fGetFileResponse\x12%\n" +
	"\x05chunk\x18\x01 \x01(\v2\x0f.sync.FileChunkR\x05chunk\"O\n" +
	"\vPutFileInit\x12\x1b\n" +
	"\troot_name\x18\x01 \x01(\tR\brootName\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\"m\n" +
	"\x0ePutFileRequest\x12'\n" +
	"\x04init\x18\x01 \x01(\v2\x11.sync.PutFileInitH\x00R\x04init\x12'\n" +
	"\x05chunk\x18\x02 \x01(\v2\x0f.sync.FileChunkH\x00R\x05chunkB\t\n" +
	"\apayload\"E\n" +
	"\x0fPutFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"U\n" +
	"\x11DeleteFileRequest\x12\x1b\n" +
	"\troot_name\x18\x01 \x01(\tR\brootName\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\"H\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"y\n" +
	"\x11RenameFileRequest\x12\x1b\n" +
	"\troot_name\x18\x01 \x01(\tR\brootName\x12\x1b\n" +
	"\tfile_uuid\x18\x02 \x01(\tR\bfileUuid\x12*\n" +
	"\x11new_relative_path\x18\x03 \x01(\tR\x0fnewRelativePath\"H\n" +
	"\x12RenameFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\tFileChunk\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data2\xcb\x02\n" +
	"\x0fFileSyncService\x12B\n" +
	"\vGetFileList\x12\x18.sync.GetFileListRequest\x1a\x19.sync.GetFileListResponse\x128\n" +
	"\aGetFile\x12\x14.sync.GetFileRequest\x1a\x15.sync.GetFileResponse0\x01\x128\n" +
	"\aPutFile\x12\x14.sync.PutFileRequest\x1a\x15.sync.PutFileResponse(\x01\x12?\n" +
	"\n" +
	"DeleteFile\x12\x17.sync.DeleteFileRequest\x1a\x18.sync.DeleteFileResponse\x12?\n" +
	"\n" +
	"RenameFile\x12\x17.sync.RenameFileRequest\x1a\x18.sync.RenameFileResponseB\x14Z\x12internal/sync;syncb\x06proto3"

var (
	file_proto_sync_proto_rawDescOnce sync.Once
	file_proto_sync_proto_rawDescData []byte
)

func file_proto_sync_proto_rawDescGZIP() []byte {
	file_proto_sync_proto_rawDescOnce.Do(func() {
		file_proto_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sync_proto_rawDesc), len(file_proto_sync_proto_rawDesc)))
	})
	return file_proto_sync_proto_rawDescData
}

var file_proto_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_sync_proto_goTypes = []any{
	(*FileMetadata)(nil),        // 0: sync.FileMetadata
	(*GetFileListRequest)(nil),  // 1: sync.GetFileListRequest
	(*GetFileListResponse)(nil), // 2: sync.GetFileListResponse
	(*GetFileRequest)(nil),      // 3: sync.GetFileRequest
	(*GetFileResponse)(nil),     // 4: sync.GetFileResponse
	(*PutFileInit)(nil),         // 5: sync.PutFileInit
	(*PutFileRequest)(nil),      // 6: sync.PutFileRequest
	(*PutFileResponse)(nil),     // 7: sync.PutFileResponse
	(*DeleteFileRequest)(nil),   // 8: sync.DeleteFileRequest
	(*DeleteFileResponse)(nil),  // 9: sync.DeleteFileResponse
	(*RenameFileRequest)(nil),   // 10: sync.RenameFileRequest
	(*RenameFileResponse)(nil),  // 11: sync.RenameFileResponse
	(*FileChunk)(nil),           // 12: sync.FileChunk
}
var file_proto_sync_proto_depIdxs = []int32{
	0,  // 0: sync.GetFileListResponse.files:type_name -> sync.FileMetadata
	12, // 1: sync.GetFileResponse.chunk:type_name -> sync.FileChunk
	5,  // 2: sync.PutFileRequest.init:type_name -> sync.PutFileInit
	12, // 3: sync.PutFileRequest.chunk:type_name -> sync.FileChunk
	1,  // 4: sync.FileSyncService.GetFileList:input_type -> sync.GetFileListRequest
	3,  // 5: sync.FileSyncService.GetFile:input_type -> sync.GetFileRequest
	6,  // 6: sync.FileSyncService.PutFile:input_type -> sync.PutFileRequest
	8,  // 7: sync.FileSyncService.DeleteFile:input_type -> sync.DeleteFileRequest
	10, // 8: sync.FileSyncService.RenameFile:input_type -> sync.RenameFileRequest
	2,  // 9: sync.FileSyncService.GetFileList:output_type -> sync.GetFileListResponse
	4,  // 10: sync.FileSyncService.GetFile:output_type -> sync.GetFileResponse
	7,  // 11: sync.FileSyncService.PutFile:output_type -> sync.PutFileResponse
	9,  // 12: sync.FileSyncService.DeleteFile:output_type -> sync.DeleteFileResponse
	11, // 13: sync.FileSyncService.RenameFile:output_type -> sync.RenameFileResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_sync_proto_init() }
func file_proto_sync_proto_init() {
	if File_proto_sync_proto != nil {
		return
	}
	file_proto_sync_proto_msgTypes[6].OneofWrappers = []any{
		(*PutFileRequest_Init)(nil),
		(*PutFileRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sync_proto_rawDesc), len(file_proto_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sync_proto_goTypes,
		DependencyIndexes: file_proto_sync_proto_depIdxs,
		MessageInfos:      file_proto_sync_proto_msgTypes,
	}.Build()
	File_proto_sync_proto = out.File
	file_proto_sync_proto_goTypes = nil
	file_proto_sync_proto_depIdxs = nil
}
